accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("student/info/", views.student_info, name="student_info"),
    path("student/edit/<str:account_id>/", views.student_edit, name="student_edit"),
    path("instructor/info/", views.instructor_info, name="instructor_info"),
    path(
        "instructor/edit/<str:account_id>/",
        views.instructor_edit,
        name="instructor_edit",
    ),
    path("student/search/", views.student_search, name="student_search"),
    path("instructor/search/", views.instructor_search, name="instructor_search"),
]

attendance/urls.py
from django.urls import path
from . import views

app_name = 'attendance'

urlpatterns = [
    path('statistic/<str:account_id>/', views.attendance_statistic, name='statistic'),
    path('statistic-detail/<str:course_id>/', views.attendance_statistic_detail, name='statistic_detail'),
    path('send-warning/<str:student_id>/<str:course_id>/', views.send_warning_email, name='send_warning_email'),
    path('history/<str:account_id>/', views.student_attendance_history, name='history'),
]

courses/urls.py
from django.urls import path
from . import views

app_name = "courses"

urlpatterns = [
    path(
        "student/<str:account_id>/schedule-week/",
        views.student_schedule_week,
        name="student_schedule_week",
    ),
    path(
        "student/<str:account_id>/schedule/",
        views.student_schedule,
        name="student_schedule",
    ),
    path(
        "instructor/<str:account_id>/schedule/",
        views.instructor_schedule,
        name="instructor_schedule",
    ),
    path(
        "instructor/<str:account_id>/schedule-week/",
        views.instructor_schedule_week,
        name="instructor_schedule_week",
    ),
    path(
        "<int:course_id>/students-list/",
        views.student_list_by_course,
        name="student_list_by_course",
    ),
    path(
        "<int:course_id>/export-attendance/",
        views.export_attendance,
        name="export_attendance",
    ),
]

student_attendance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='layouts/home.html'), name='home'),
    path('accounts/', include('accounts.urls')),
    path('courses/', include('courses.urls')),
    path('face_recognition/', include('face_recognition.urls')),
    path('attendance/', include('attendance.urls')),
    path('admin/', admin.site.urls),
]

templates/layouts/base.html
<!DOCTYPE html>
<html lang="vi">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Student Portal{% endblock %}</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <style>
        body {
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            background-color: #f5f5f5;
        }

        .sidebar {
            width: 250px;
            height: 100vh;
            background-color: #fff;
            box-shadow: 2px 0 5px rgba(0, 0, 0, 0.1);
            position: fixed;
            display: flex;
            flex-direction: column;
        }

        .sidebar .menu {
            list-style: none;
            padding: 0;
            margin: 0;
        }

        .sidebar .menu li {
            width: 100%;
        }

        .sidebar .menu a {
            display: block;
            padding: 15px 20px;
            text-decoration: none;
            color: #34495e;
            font-size: 16px;
            transition: background-color 0.3s, color 0.3s;
        }

        .sidebar .menu a:hover,
        .sidebar .menu a.active {
            background-color: rgb(77, 144, 254);
            color: #fff;
            border-radius: 5px;
        }

        .navbar {
            height: 60px;
            background-color: rgb(77, 144, 254);
            color: #000000;
            display: flex;
            align-items: center;
            justify-content: flex-end;
            position: fixed;
            top: 0;
            left: 250px;
            width: calc(100% - 250px);
            z-index: 1000;
        }

        .main-content {
            margin-left: 250px;
            padding: 20px;
            padding-top: 80px;
            overflow-y: auto;
            background-color: #f5f5f5;
            position: relative;
        }

        .sidebar .logo {
            display: flex;
            align-items: center;
            justify-content: center;
            margin: 0;
            padding: 0;
        }

        .sidebar .logo img {
            display: block;
            width: 50%;
            height: 90%;
        }

        .stat-box {
            background: white;
            padding: 10px 30px;
            border-radius: 10px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            border: 2px solid #00bfff;
        }

        /* Thiết kế card */
        .upload-card {
            width: 100%;
            background: white;
            border-radius: 8px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            text-align: center;
        }

        /* Input file đẹp hơn */
        #imageUpload {
            display: block;
            width: 100%;
            margin: 10px 0;
        }

        /* Nút gửi ảnh */
        .btn-upload {
            display: inline-block;
            padding: 10px 15px;
            background: #007bff;
            color: white;
            text-decoration: none;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .btn-upload:hover {
            background: #0056b3;
        }

        .profile-row {
            display: flex;
            justify-content: space-between;
            flex-wrap: wrap;
        }

        .profile-column {
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            padding: 16px;
        }

        @media (min-width: 992px) {
            .profile-column:first-child {
                width: 40%;
            }

            .profile-column:last-child {
                width: 58%;
            }
        }

        @media (max-width: 991.98px) {
            .profile-column {
                width: 100%;
                margin-top: 15px;
            }
        }
    </style>
</head>

<body>
    <!-- Sidebar -->
    <div class="sidebar">
        <div class="logo">
            <img src="/static/images/logo.png" alt="" />
        </div>
        <ul class="menu">
            <li>
                <a href="{% if user.role == 'instructor' %}
                {% url 'accounts:instructor_info' %}
             {% else %}
                {% url 'accounts:student_info' %}
             {% endif %}">
                    <i class="fas fa-home"></i> Tổng quan
                </a>
            </li>
            {% if user.role != 'student' %}
            <li>
                <a href="{% url 'courses:instructor_schedule' account_id=user.account_id %}">
                    <i class="fas fa-calendar-alt"></i> Lịch dạy hôm nay
                </a>
            </li>
            {% endif %}
            <li>
                <a href="{% if user.role == 'instructor' %}
                                        {% url 'courses:instructor_schedule' account_id=user.account_id %}
                                     {% else %}
                                        {% url 'courses:student_schedule' account_id=user.account_id %}
                                     {% endif %}">
                    <i class="fas fa-calendar-alt"></i>
                    {% if user.role == 'instructor' %} Lịch dạy hôm nay {% else %} Lịch
                    học hôm nay {% endif %}
                </a>
            </li>
            <li>
                <a href="{% if user.role == 'instructor' %}
                            {% url 'courses:instructor_schedule_week' account_id=user.account_id %}
                         {% else %}
                            {% url 'courses:student_schedule_week' account_id=user.account_id %}
                         {% endif %}">
                    <i class="fas fa-calendar-alt"></i>
                    {% if user.role == 'instructor' %} Lịch dạy tuần {% else %} Lịch
                    học tuần {% endif %}
                </a>
            </li>

            {% if user.role == 'instructor' %}
            <li>
                <a href="{% url 'attendance:statistic' account_id=user.account_id %}"><i
                        class="fa-solid fa-comment me-1"></i>Thống kê</a>
            </li>
            {% endif %}
            
            {% if user.role == 'student' %}
            <li>
                <a href="{% url 'attendance:history' account_id=user.account_id %}" class="nav-link me-3">
                    <i class="fas fa-history me-1"></i> Lịch sử điểm danh
                </a>
            </li>
            {% endif %}
            <li>
                <a href="#"><i class="fa-solid fa-gear me-1"></i>Cài đặt</a>
            </li>
            {% if user.role == 'student' %}
            <li>
                <a href="{% url 'accounts:student_search' %}"><i class="fas fa-search"></i> Tìm kiếm</a>
            </li>
            {% endif %}
            {% if user.role == 'instructor' %}
            <li>
                <a href="{% url 'accounts:instructor_search' %}"><i class="fas fa-search"></i> Tìm kiếm</a>
            </li>
            {% endif %}
        </ul>
    </div>

    <!-- Navbar -->
    <nav class="navbar">
        <div class="dropdown ms-auto me-2">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown">
                <i class="fas fa-user"></i> {{ user.full_name }}
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
                <li>
                    <a class="dropdown-item" href="{% url 'accounts:logout' %}">
                        <i class="fas fa-sign-out-alt me-2"></i> Đăng xuất
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- Main Content -->
    <div class="main-content">{% block content %}{% endblock %}</div>

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

templates/layouts/home.html
<!DOCTYPE html>
<html lang="vi">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Trang Chủ</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  <style>
    body {
      background-color: #f8f9fa;
    }

    .hero-section {
      display: flex;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      background-color: #e9f5ff;
      padding: 20px;
    }

    .hero-content {
      max-width: 600px;
      text-align: center;
    }

    .hero-content h1 {
      font-size: 2.5rem;
      font-weight: bold;
      color: #333;
    }

    .hero-content p {
      font-size: 1.2rem;
      color: #555;
      margin-bottom: 20px;
    }

    .hero-content .btn-primary {
      font-size: 1.2rem;
      padding: 10px 20px;
      border-radius: 25px;
    }

    .hero-image {
      max-width: 500px;
      margin-left: 20px;
    }

    .hero-image img {
      width: 100%;
      border-radius: 10px;
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }
  </style>
</head>

<body>
  <div class="hero-section">
    <div class="hero-content">
      <h1>WELCOME TO THE</h1>
      <h2 class="text-primary">Da Nang University of Science and Technology</h2>
      <p>Quản lý lịch dạy, điểm danh và thông tin cá nhân một cách dễ dàng.</p>
      <div>
        {% if user.is_authenticated %}
        {% if user.role == "instructor" %}
        <a href="{% url 'accounts:instructor_info' %}" class="btn btn-primary">Vào trang thông tin</a>
        {% elif user.role == "student" %}
        <a href="{% url 'accounts:student_info' %}" class="btn btn-primary">Vào trang thông tin</a>
        {% endif %}
        {% else %}
        <a href="{% url 'accounts:login' %}" class="btn btn-primary">Đăng nhập</a>
        {% endif %}
      </div>
    </div>
    <div class="hero-image">
      <img src="/static/images/university.png" alt="University Image">
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>